In [1]:
import json
from pathlib import Path

import numpy as np
import pandas as pd

In [2]:
base_dir = Path(".").resolve()
data_dir = base_dir / "data"

In [3]:
def process_list(row):
    if row is None:
        return []
    else:
        return [int(item) for item in row if isinstance(item, str) and item.isdigit()]

In [4]:
# Distribution Rules

with open(data_dir / "metadata.json") as f:
    metadata = json.load(f)

with open(data_dir / "distribution_rules.json") as f:
    distribution_rules = json.load(
        f, object_hook=lambda obj: {**obj.pop("lvl", {}), **obj}
    )

rules = distribution_rules.get("rules", [])

for rule in rules:
    rrg = rule.get("rrg")
    if rrg is None:
        rule["rrg"] = {}

    for key in list(rule.keys()):
        if key in metadata:
            rule[metadata[key]] = rule.pop(key)

    level_mapping = metadata["level_mapping"]
    for key, value in rule.items():
        if isinstance(value, dict):
            for k in list(value.keys()):
                if k in level_mapping:
                    value[level_mapping[k]] = value.pop(k)

df_rules = pd.json_normalize(rules, sep="_")
df_rules["credential_list"] = df_rules["credential_list"].apply(process_list)
df_rules["credential_count"] = df_rules["credential_list"].apply(len)
df_rules["provider_list"] = df_rules["provider_list"].apply(
    lambda x: x if x is not None else []
)
df_rules["provider_count"] = df_rules["provider_list"].apply(len)
df_rules["hotel_list"] = df_rules["hotel_list"].apply(process_list)
df_rules["hotel_count"] = df_rules["hotel_list"].apply(len)
df_rules = df_rules[
    [
        "id",
        "edit_state",
        "obsolete",
        "name",
        "description",
        "tag",
        "credential_choices",
        "credential_list",
        "credential_count",
        "rate",
        "provider_choices",
        "provider_list",
        "provider_count",
        "hotel_choices",
        "hotel_list",
        "hotel_count",
        "destination_choices",
        "destination_list",
        "refundable",
        "meal_choices",
        "meal_list",
        "market_choices",
        "market_list",
        "dynamic_commission",
        "check_in_choices",
        "check_in_from",
        "check_in_to",
        "booking_date_choices",
        "booking_date_from",
        "booking_date_to",
        "range_choices",
        "range_from",
        "range_to",
        "max_release",
        "days_of_week_choices",
        "days_of_week_list",
        "age",
        "room_choices",
        "room_list",
        "ps_choices",
        "ps_list",
        "num_of_nights_choices",
        "num_of_nights_list",
        "hours_choices",
        "hours_list",
        "updated_by",
        "updated_on",
    ]
]

In [5]:
with pd.option_context("display.max_columns", None):
    display(df_rules.head())

,id,edit_state,obsolete,name,description,tag,credential_choices,credential_list,credential_count,rate,provider_choices,provider_list,provider_count,hotel_choices,hotel_list,hotel_count,destination_choices,destination_list,refundable,meal_choices,meal_list,market_choices,market_list,dynamic_commission,check_in_choices,check_in_from,check_in_to,booking_date_choices,booking_date_from,booking_date_to,range_choices,range_from,range_to,max_release,days_of_week_choices,days_of_week_list,age,room_choices,room_list,ps_choices,ps_list,num_of_nights_choices,num_of_nights_list,hours_choices,hours_list,updated_by,updated_on
0,394291,1,False,Abades El MIrador,CDH-271194,1,1,"[5226, 8550]",2,0,1,"[SMD, BCONG]",2,1,[1727],1,0,[],0,0,None,0,None,False,0,None,None,0,None,None,0.0,0.0,0.0,0,0,None,0,0,None,0,None,0,None,0,None,maria.ulloa@traveltino.com,27-04-2023 17:52:11
1,432673,1,False,Cierre todo SMY Sheraton FUE,CDH-12945,1,0,[],0,0,1,"[DNG, BCONG, ELBA]",3,1,[141023],1,0,[],0,0,None,0,None,False,0,None,None,0,None,None,0.0,0.0,0.0,0,0,None,0,0,None,0,None,0,None,0,None,maria.ulloa@traveltino.com,09-04-2024 14:01:56
2,498300,1,False,NRF next 15 dias,Stop sales for NRF 15 days in adv to the futur...,1,1,"[11807, 5318]",2,0,0,[],0,0,[],0,0,[],1,0,None,0,None,False,0,None,None,0,None,None,1.0,15.0,9999.0,0,0,None,0,0,None,0,None,0,None,0,None,daniel.diez@smyrooms.com,17-07-2024 11:38:14
3,394034,1,False,Close Landmar Costa Gigantes to Atrapalo,Close Landmar Costa Gigantes to Atrapalo,3,1,"[10206, 8456]",2,0,1,"[TRVR, AXI, AXL, AXT, AXK, AXR, MTSUK, TRVD, T...",11,1,[148975],1,0,None,0,0,None,0,None,False,0,None,None,0,None,None,0.0,0.0,0.0,0,0,None,0,0,None,0,None,0,None,0,None,pau.cespedes@logitravelgroup.com,21-09-2022 11:46:13
4,394446,1,False,Cierre de ventas en el hotel Abba Berlin,CDH-274118,1,1,"[5997, 10901, 32713, 5129, 5226, 30830, 31318,...",59,0,1,[BCONG],1,1,[446424],1,0,[],0,0,None,0,None,False,0,None,None,0,None,None,0.0,0.0,0.0,0,0,None,0,0,None,0,None,0,None,0,None,miguel.fuentes@traveltino.com,25-01-2023 09:53:55

In [6]:
df_rules = df_rules.loc[df_rules["id"].isin(["16630", "658475", "395771", "395344"])]
df_rules = df_rules.sort_values(by="credential_count", ascending=False)
df_rules["id"] = df_rules["id"].astype(int)

In [7]:
df_exploded = (
    df_rules.explode("credential_list").explode("provider_list").explode("hotel_list")
)

In [8]:
df_exploded["combination_zip"] = list(
    zip(
        df_exploded["credential_list"],
        df_exploded["provider_list"],
        df_exploded["hotel_list"],
    )
)

In [9]:
with pd.option_context("display.max_columns", None):
    display(df_exploded.head())

,id,edit_state,obsolete,name,description,tag,credential_choices,credential_list,credential_count,rate,provider_choices,provider_list,provider_count,hotel_choices,hotel_list,hotel_count,destination_choices,destination_list,refundable,meal_choices,meal_list,market_choices,market_list,dynamic_commission,check_in_choices,check_in_from,check_in_to,booking_date_choices,booking_date_from,booking_date_to,range_choices,range_from,range_to,max_release,days_of_week_choices,days_of_week_list,age,room_choices,room_list,ps_choices,ps_list,num_of_nights_choices,num_of_nights_list,hours_choices,hours_list,updated_by,updated_on,combination_zip
907,16630,1,False,Be live,No podemos distribuir a Expedia (entra dentro ...,1,1,5997,56,0,1,DNG,4,1,647852,27,0,[],0,0,None,0,None,False,0,None,None,0,None,None,0.0,0.0,0.0,0,0,None,0,0,None,0,None,0,None,0,None,maria.ulloa@traveltino.com,19-05-2023 10:38:12,"(5997, DNG, 647852)"
907,16630,1,False,Be live,No podemos distribuir a Expedia (entra dentro ...,1,1,5997,56,0,1,DNG,4,1,68062,27,0,[],0,0,None,0,None,False,0,None,None,0,None,None,0.0,0.0,0.0,0,0,None,0,0,None,0,None,0,None,0,None,maria.ulloa@traveltino.com,19-05-2023 10:38:12,"(5997, DNG, 68062)"
907,16630,1,False,Be live,No podemos distribuir a Expedia (entra dentro ...,1,1,5997,56,0,1,DNG,4,1,224201,27,0,[],0,0,None,0,None,False,0,None,None,0,None,None,0.0,0.0,0.0,0,0,None,0,0,None,0,None,0,None,0,None,maria.ulloa@traveltino.com,19-05-2023 10:38:12,"(5997, DNG, 224201)"
907,16630,1,False,Be live,No podemos distribuir a Expedia (entra dentro ...,1,1,5997,56,0,1,DNG,4,1,36031,27,0,[],0,0,None,0,None,False,0,None,None,0,None,None,0.0,0.0,0.0,0,0,None,0,0,None,0,None,0,None,0,None,maria.ulloa@traveltino.com,19-05-2023 10:38:12,"(5997, DNG, 36031)"
907,16630,1,False,Be live,No podemos distribuir a Expedia (entra dentro ...,1,1,5997,56,0,1,DNG,4,1,221223,27,0,[],0,0,None,0,None,False,0,None,None,0,None,None,0.0,0.0,0.0,0,0,None,0,0,None,0,None,0,None,0,None,maria.ulloa@traveltino.com,19-05-2023 10:38:12,"(5997, DNG, 221223)"

In [10]:
duplicate_ids = df_exploded.groupby("combination_zip")["id"].apply(list).to_dict()

In [11]:
df_exploded["duplicate_ids"] = df_exploded["combination_zip"].map(duplicate_ids)

In [15]:
df_exploded.drop_duplicates(subset=["combination_zip"], keep="first", inplace=True)

In [16]:
df_exploded = (
    df_exploded.groupby("id")
    .agg(
        {
            "credential_list": lambda x: list(set(x)),
            "provider_list": lambda x: list(set(x)),
            "hotel_list": lambda x: list(set(x)),
            "duplicate_ids": "first",
        }
    )
    .reset_index()
)

In [17]:
df_exploded.to_csv("df_exploded.csv", index=False)